name = "DataEnvelopmentAnalysis"
uuid = "a100299e-89d6-11e9-0fa0-2daf497e6a05"
authors = ["Javier Barbero"]
version = "0.9.2"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributed = "1.6"
Distributions = "0.25"
GLPK = "1"
InvertedIndices = "^1.1"
Ipopt = "1"
JuMP = "1"
LinearAlgebra = "1.6"
PrecompileTools = "1"
Printf = "1.6"
ProgressMeter = "^1.7"
Random = "1.6"
SharedArrays = "1.6"
SparseArrays = "1.6"
Statistics = "1"
StatsAPI = "1.5"
StatsBase = "0.33, 0.34"
julia = "1.6"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Distributions", "StableRNGs", "Random"]
